project:
  type: website
  output-dir: docs

website:
  title: "Saba Hanani"
  navbar:
    background: "#F5A3D8"
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - Projects.qmd

format:
  html:
    theme: simplex
    mainfont: arial
    fontsize: 1rem
    monofont: courier new
    css: styles.css
    toc: true



